version: "3.9"
services:
  chatbot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BASE_URL=http://ollama:11434
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=chatbot_db
      - COLLECTION_NAME=courses
    depends_on:
      - ollama
      - mongo
    networks:
      - chatbot-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"  # tourne sur localhost:11435
    volumes:
      - ./model_files:/model_files  
    tty: true
    networks:
      - chatbot-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge

volumes:
  mongo-data:
