name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y portaudio19-dev  # For Ubuntu

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Upgrade pip and tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies with retries
        run: |
          for i in 1 2 3; do pip install -r requirements.txt && break || sleep 10; done

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Run tests with pytest
        run: |
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Upgrade pip and tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies with retries
        run: |
          for i in 1 2 3; do pip install -r requirements.txt && break || sleep 10; done

      - name: Deploy to Streamlit
        run: |
          streamlit run app.py --server.port 8501