name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y portaudio19-dev  # For Ubuntu

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Upgrade pip and tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies with retries
        run: |
          for i in 1 2 3; do pip install -r requirements.txt && break || sleep 10; done

      - name: Run tests with pytest
        run: pytest src/test_utils.py

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub securely
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t chatbot-app .
          docker tag chatbot-app ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-app:latest

